version: 2

models:
  - name: dim_pcns
    description: "Dimension table for Primary Care Networks (PCNs)"
    columns:
      - name: pcn_id
        description: "Primary key for PCNs"
        tests:
          - unique
          - not_null
      - name: pcn_name
        description: "Name of the Primary Care Network"
        tests:
          - unique
          - not_null
  - name: dim_practices
    description: "Dimension table for practices"
    columns:
      - name: practice_id
        description: "Primary key for practices"
        tests:
          - unique
          - not_null
      - name: pcn_id
        description: "Foreign key to dim_pcns"
        tests:
          - not_null
          - relationships:
              to: ref('dim_pcns')
              field: pcn_id
      - name: practice_name
        description: "Name of the practice"
        tests:
          - not_null
      - name: location
        description: "Location of the practice"
      - name: established_date
        description: "Date when the practice was established"
  - name: dim_patients
    description: "Dimension table for patients"
    columns:
      - name: patient_id
        description: "Primary key for patients"
        tests:
          - unique
          - not_null
      - name: practice_id
        description: "Foreign key to dim_practices"
        tests:
          - relationships:
              to: ref('dim_practices')
              field: practice_id
      - name: age
        description: "Age of the patient"
      - name: age_group
        description: "Age group of the patient"
      - name: gender
        description: "Gender of the patient"
        tests:
          - accepted_values:
              values: ['F', 'M'] # Assumption: only 'F' and 'M' are found in the dataset
      - name: registration_date
        description: "Date when the patient registered with the practice"
      - name: conditions
        description: "Medical conditions of the patient"
      - name: phone_number
        description: "Phone number of the patient"
      - name: email
        description: "Email address of the patient"
  - name: fact_activities
    description: "Fact table for patient activities"
    columns:
      - name: activity_id
        description: "Primary key for activities"
        tests:
          - unique
          - not_null
      - name: patient_id
        description: "Foreign key to dim_patients"
        tests:
          - not_null
          - relationships:
              to: ref('dim_patients')
              field: patient_id
      - name: activity_type
        description: "Type of activity (e.g., appointment, consultation)"
        tests:
          - accepted_values:
              values: ['prescription', 'consultation', 'intro_call', 'edge_case', 'lab_test', 'after_hours']
      - name: activity_date
        description: "Date of the activity"
        tests:
          - not_null
      - name: duration_minutes
        description: "Duration of the activity in minutes"
